# Generated by Django 5.0.4 on 2024-05-10 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0002_alter_producto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='fecha_creacion',
        ),
    ]
