# Generated by Django 5.0.6 on 2024-05-15 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='productos/')),
                ('en_oferta', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_ferremas.categoriaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoOferta',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web_ferremas.producto')),
                ('precio_oferta', models.IntegerField(default=0)),
            ],
        ),
    ]
