# Generated by Django 5.0.4 on 2024-05-25 02:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ferremas', '0004_tipoproducto_remove_producto_categoria_producto_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('direccion_envio', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_ferremas.carrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_ferremas.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_ferremas.pedido')),
            ],
        ),
    ]
