# Generated by Django 5.0.4 on 2024-05-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ferremas', '0007_carrito_pedido_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pendiente de pago', 'Pendiente de Pago'), ('aprobado', 'Aprobado'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
