# Generated by Django A.B on YYYY-MM-DD HH:MM
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('web_ferremas', '0009_pedido_payment_token_alter_pedido_estado'),
        ('web_ferremas', '0010_auto_20240526_2335'),
    ]

    operations = [
        # Aquí se pueden listar las operaciones de merge si las hay
    ]
