# Generated by Django 5.0.4 on 2024-06-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ferremas', '0012_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='tipo',
            field=models.TextField(),
        ),
    ]
